.travis.yml:
  envs:
    - puppet: 2.7.0
    - puppet: 3.1.0
    - puppet: 3.2.0
    - puppet: 3.3.0
    - puppet: 3.4.0
    - puppet: 3.5.0
      facter: 2.0
    - puppet: 3.5.0
      facter: 1.7
    - puppet: 3.6.0
      facter: 2.0
    - puppet: 3.6.0
      facter: 1.7
    - puppet: 3.7.0
      facter: 2.0
    - puppet: 3.7.0
      facter: 1.7
Gemfile:
  optional:
    - gem: yard
